name: FineTuningSageMaker
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - boto3=1.29.1
  - botocore=1.32.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jmespath=1.0.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libcxx=14.0.6
  - libffi=3.3
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=1.1.1w
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.1
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pyzmq=24.0.1
  - readline=8.2
  - s3transfer=0.7.0
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.13.0
  - typing_extensions=4.8.0
  - urllib3=2.0.3
  - wcwidth=0.2.10
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.0
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==2.2.1
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - dataclasses-json==0.6.2
      - datasets==2.15.0
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fonttools==4.44.3
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-pasta==0.2.0
      - greenlet==3.0.1
      - hf-transfer==0.1.4
      - huggingface-hub==0.19.4
      - idna==3.4
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - kiwisolver==1.4.5
      - langchain==0.0.338
      - langsmith==0.0.65
      - levenshtein==0.23.0
      - marshmallow==3.20.1
      - matplotlib==3.8.2
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - numpy==1.26.2
      - pandas==2.1.3
      - pathos==0.3.1
      - pillow==10.1.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - protobuf==4.25.1
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.5
      - pydantic==2.5.1
      - pydantic-core==2.14.3
      - pyparsing==3.1.1
      - python-dotenv==1.0.0
      - python-levenshtein==0.23.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - rapidfuzz==3.5.2
      - referencing==0.31.0
      - regex==2023.10.3
      - requests==2.31.0
      - rpds-py==0.13.0
      - safetensors==0.4.0
      - sagemaker==2.197.0
      - schema==0.7.5
      - seaborn==0.13.0
      - sentry-sdk==1.36.0
      - setproctitle==1.3.3
      - smdebug-rulesconfig==1.0.1
      - smmap==5.0.1
      - sniffio==1.3.0
      - sqlalchemy==2.0.23
      - tblib==1.7.0
      - tenacity==8.2.3
      - tokenizers==0.15.0
      - tqdm==4.66.1
      - transformers==4.35.2
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - wandb==0.16.0
      - xxhash==3.4.1
      - yarl==1.9.2
